# -*- coding: utf-8 -*-
"""svd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bYIPnMTkTqauZ8wVaEsVx8LFKjXdJXW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

!pip install mne

import mne

raw = mne.io.read_raw_edf('ходьба_4км.edf')

raw.info

raw.ch_names

new_names = ['ANX1',
 'ANY1',
 'ANZ1',
 'ACY4',
 'GRZ4',
 'ACY5',
 'GRZ5',
 'CoxFlexL',
 'CoxFlexR',
 'CoxAddL',
 'CoxAddR',
 'CoxPronL',
 'CoxPronR',
 'GenFlexL',
 'GenFlexR',
 'GenAddL',
 'GenAddR',
 'GenPronL',
 'GenPronR',
 'TalFlexL',
 'TalFlexR',
 'TalPronL',
 'TalPronR']

raw.rename_channels(dict(zip(raw.ch_names, new_names)))

raw.ch_names

data = raw['data'][0]

"""# SVD"""

x = data[:23, 2048:2048*15]
x

U, S, Vh = np.linalg.svd(x, full_matrices=False)
U.shape, S.shape, Vh.shape

!pip install seaborn

sns.barplot(data = S)